'use client'

export default function TermsOfServicePage() {
  const sectionStyle = { marginBottom: '32px' }
  const h2Style = { fontSize: '20px', fontWeight: 800, color: '#1a3a5c', marginBottom: '12px' }
  const pStyle = { fontSize: '15px', color: '#444', lineHeight: 1.7, marginBottom: '12px' }
  const liStyle = { fontSize: '15px', color: '#444', lineHeight: 1.7, marginBottom: '8px' }

  return (
    <main style={{ fontFamily: 'system-ui, -apple-system, sans-serif', color: '#1a1a1a', background: '#fff', minHeight: '100vh' }}>
      <nav style={{ borderBottom: '1px solid #e5e7eb', padding: '0 2rem' }}>
        <div style={{ maxWidth: '760px', margin: '0 auto', display: 'flex', alignItems: 'center', justifyContent: 'space-between', height: '64px' }}>
          <a href="/landing" style={{ display: 'flex', alignItems: 'center', gap: '10px', textDecoration: 'none' }}>
            <div style={{ width: '32px', height: '32px', background: '#1a3a5c', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <span style={{ color: '#fff', fontWeight: 700, fontSize: '14px' }}>J</span>
            </div>
            <span style={{ fontWeight: 700, fontSize: '16px', color: '#1a3a5c' }}>JOANResearchOS</span>
          </a>
          <a href="/" style={{ color: '#2e75b6', textDecoration: 'none', fontSize: '14px', fontWeight: 600 }}>← Back to app</a>
        </div>
      </nav>

      <div style={{ maxWidth: '760px', margin: '0 auto', padding: '60px 2rem 100px' }}>
        <h1 style={{ fontSize: '32px', fontWeight: 800, color: '#1a3a5c', marginBottom: '8px' }}>Terms of Service</h1>
        <p style={{ fontSize: '14px', color: '#888', marginBottom: '48px' }}>Last updated: June 30, 2026</p>

        <div style={sectionStyle}>
          <p style={pStyle}>
            These terms govern your use of JOANResearchOS. By creating an account or using the service, you agree to them.
            If you're using JOANResearchOS on behalf of an institution, you're confirming you have authority to accept
            these terms for that institution.
          </p>
        </div>

        <div style={sectionStyle}>
          <h2 style={h2Style}>1. What JOANResearchOS Is</h2>
          <p style={pStyle}>
            JOANResearchOS is a tool that helps you select an appropriate statistical test, generates R code to perform
            it, executes that code on a dedicated R server, and writes a plain-language interpretation of the results.
            <strong> All statistical computation — every p-value, confidence interval, risk ratio, and effect size — is
            performed exclusively by R, never estimated or generated by AI.</strong> Every analysis includes the full R
            script and raw R console output so results can be independently verified.
          </p>
        </div>

        <div style={sectionStyle}>
          <h2 style={h2Style}>2. Not a Substitute for Professional Judgment</h2>
          <p style={pStyle}>
            JOANResearchOS is a research support tool. It does not replace the judgment of a qualified biostatistician,
            epidemiologist, clinician, or your institution's ethics review process. You are responsible for reviewing
            the generated R script and output, verifying that the selected statistical test was appropriate for your
            data and research question, and ensuring any report submitted to DOH, WHO, an ethics board, or a publication
            meets that body's own standards before submission.
          </p>
        </div>

        <div style={sectionStyle}>
          <h2 style={h2Style}>3. Acceptable Use</h2>
          <p style={pStyle}>You agree to:</p>
          <ul style={{ paddingLeft: '20px', marginBottom: '12px' }}>
            <li style={liStyle}>Upload only de-identified data — no real patient names, exact addresses, or other directly identifying information</li>
            <li style={liStyle}>Use the service in compliance with your institution's data governance policies and applicable law</li>
            <li style={liStyle}>Not attempt to circumvent usage limits, rate limits, or security controls</li>
            <li style={liStyle}>Not use the service to process data you do not have the right to analyze</li>
          </ul>
          <p style={pStyle}>We reserve the right to suspend accounts that violate these terms.</p>
        </div>

        <div style={sectionStyle}>
          <h2 style={h2Style}>4. Plans, Billing, and Payment</h2>
          <p style={pStyle}>
            The Free plan includes 5 analyses per month at no cost. Pro and Institution plans are billed monthly via
            manual GCash or bank transfer — there is no automatic recurring card payment. To upgrade, contact us using
            the link on the pricing page; we will send payment instructions and activate your new plan within 24 hours
            of confirming payment. Plan downgrades or cancellations should also be requested by email; downgrades take
            effect at the end of the current billing period unless otherwise agreed.
          </p>
        </div>

        <div style={sectionStyle}>
          <h2 style={h2Style}>5. Your Data</h2>
          <p style={pStyle}>
            You retain ownership of the datasets you upload and the research questions you submit. By using the
            service, you grant us permission to process that data solely to provide the analysis, store your history,
            and operate the platform, as described in our{' '}
            <a href="/privacy" style={{ color: '#2e75b6' }}>Privacy Policy</a>. We do not use your data to train AI models.
          </p>
        </div>

        <div style={sectionStyle}>
          <h2 style={h2Style}>6. Service Availability</h2>
          <p style={pStyle}>
            JOANResearchOS runs on third-party infrastructure (Vercel, Supabase, Render.com) and we do our best to keep
            it available, but we do not guarantee uninterrupted access. The R execution server may occasionally take
            up to 30 seconds to respond after a period of inactivity — this is expected behavior, not a malfunction.
          </p>
        </div>

        <div style={sectionStyle}>
          <h2 style={h2Style}>7. Limitation of Liability</h2>
          <p style={pStyle}>
            JOANResearchOS is provided "as is." To the fullest extent permitted by law, we are not liable for decisions
            made based on analysis results, for data loss, or for any indirect or consequential damages arising from
            use of the service. You remain responsible for independently verifying any result before relying on it for
            clinical, regulatory, or publication purposes.
          </p>
        </div>

        <div style={sectionStyle}>
          <h2 style={h2Style}>8. Changes to These Terms</h2>
          <p style={pStyle}>We may update these terms from time to time. Continued use of the service after an update constitutes acceptance of the revised terms.</p>
        </div>

        <div style={sectionStyle}>
          <h2 style={h2Style}>9. Governing Law</h2>
          <p style={pStyle}>These terms are governed by the laws of the Republic of the Philippines.</p>
        </div>

        <div style={sectionStyle}>
          <h2 style={h2Style}>10. Contact</h2>
          <p style={pStyle}>
            Questions about these terms can be sent to{' '}
            <a href="mailto:yolymarorfiano@yahoo.com" style={{ color: '#2e75b6' }}>yolymarorfiano@yahoo.com</a>.
          </p>
        </div>
      </div>

      <footer style={{ background: '#060f1a', padding: '24px 2rem', textAlign: 'center' }}>
        <p style={{ color: '#4a6a85', fontSize: '13px' }}>
          <a href="/landing" style={{ color: '#4a6a85' }}>JOANResearchOS</a> ·{' '}
          <a href="/privacy" style={{ color: '#4a6a85' }}>Privacy Policy</a>
        </p>
      </footer>
    </main>
  )
}
